

# This file was *autogenerated* from the file nft_id_generator.sage
from sage.all_cmdline import *   # import sage library

_sage_const_21888242871839275222246405745257275088548364400416034343698204186575808495617 = Integer(21888242871839275222246405745257275088548364400416034343698204186575808495617); _sage_const_0 = Integer(0); _sage_const_256 = Integer(256); _sage_const_64 = Integer(64); _sage_const_1 = Integer(1)
from sage.all import *

# Define the BN254 curve parameters
p = _sage_const_21888242871839275222246405745257275088548364400416034343698204186575808495617 
F = GF(p)

# Create the NFT_ID_LIST with random numbers modulo p
NFT_ID_LIST = [[F.random_element(), F.random_element()] for i in (ellipsis_range(_sage_const_0 ,Ellipsis,_sage_const_256 ))]

# Print the NFT_ID_LIST
print("global NFT_ID_LIST: [[Field; 2]; 256] = [")
for i in range(_sage_const_0 ,_sage_const_256 ):
    nft_id_0 = "0x" + hex(NFT_ID_LIST[i][_sage_const_0 ]).replace('0x','').zfill(_sage_const_64 )
    nft_id_1 = "0x" + hex(NFT_ID_LIST[i][_sage_const_1 ]).replace('0x','').zfill(_sage_const_64 )
    print("[" + nft_id_0 +", " + nft_id_1 + " ],")
print("]")

